const SUBJECTS={chinese:{name:"语文",icon:"📖",color:"#ffe6dc",i:0},math:{name:"数学",icon:"🧮",color:"#e5e0ff",i:1},english:{name:"英语",icon:"🎧",color:"#dcf5ed",i:2}},RUBRIC=[["任务完成度",30],["练习正确率",25],["专注与习惯",15],["错题订正",15],["拓展学习",10],["自我总结",5]],KEY="starStudyV2",$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let data=JSON.parse(localStorage.getItem(KEY)||"null")||{name:"小小探索家",pin:"1234",start:new Date().toISOString().slice(0,10),tasks:{},records:{}},currentSubject="";
const dateKey=d=>d.toISOString().slice(0,10),today=()=>dateKey(new Date()),save=()=>localStorage.setItem(KEY,JSON.stringify(data)),todayRecords=()=>data.records[today()]||{};
function position(){const n=Math.max(0,Math.floor((new Date(today())-new Date(data.start))/86400000));return{week:Math.min(7,Math.floor(n/7)),day:n%7}}
function assigned(id){const p=position(),s=SUBJECTS[id];return data.tasks[today()]?.[id]||planTask(p.week,p.day,s.i)}
function init(){$("#dateText").textContent=new Intl.DateTimeFormat("zh-CN",{month:"long",day:"numeric",weekday:"long"}).format(new Date());$("#weekNo").textContent=position().week+1;$(".hero h1").textContent=`早上好，${data.name} 🌱`;renderTasks();renderPlan();renderAll()}
function renderTasks(){const r=todayRecords();$("#taskList").innerHTML=Object.entries(SUBJECTS).map(([id,s])=>`<article class="task ${r[id]?"done":""}"><div class="task-icon" style="background:${s.color}">${s.icon}</div><div><h3>${s.name} ${r[id]?`<span class="score">${r[id].score}分</span>`:""}</h3><p>${assigned(id)}</p><div class="task-actions"><button class="learn-btn" data-learn="${id}">开始学习</button><button data-score="${id}">${r[id]?"查看评分":"评分"}</button></div></div></article>`).join("");$$("[data-score]").forEach(b=>b.onclick=()=>openScore(b.dataset.score));$$("[data-learn]").forEach(b=>b.onclick=()=>openLesson(b.dataset.learn))}
function openLesson(id){currentSubject=id;const s=SUBJECTS[id],p=position(),lesson=lessonFor(id,p,assigned(id));$("#lessonIcon").textContent=s.icon;$("#lessonMeta").textContent=`第${p.week+1}周 · 第${p.day+1}天 · ${s.name}`;$("#lessonTitle").textContent=lesson.title;$("#lessonBody").innerHTML=`<div class="lesson-block today-learn"><b>今日任务</b><p>${lesson.taskText}</p><p>${lesson.dayStep}</p></div><div class="lesson-block"><h3>学习目标</h3><ul>${lesson.goals.map(x=>`<li>${x}</li>`).join("")}</ul></div><div class="lesson-block"><h3>知识讲解</h3>${lesson.teach.map(x=>`<p>${x}</p>`).join("")}</div><div class="lesson-block example"><h3>例题讲解</h3><p><b>题目：</b>${lesson.example.q}</p><p><b>解析：</b>${lesson.example.a}</p></div><div class="lesson-block"><h3>随堂练习</h3>${lesson.practice.map((q,i)=>`<label class="quiz"><span>${i+1}. ${q[0]}</span><input type="text" data-answer="${q[1]}" placeholder="在这里输入答案"><small></small></label>`).join("")}<button type="button" class="check-btn" id="checkLesson">检查答案</button></div><div class="lesson-block summary"><h3>今日小结</h3><p>${lesson.summary}</p></div>`;$("#lessonDialog").showModal();$("#checkLesson").onclick=checkLesson}
function normAnswer(x){return String(x||"").toLowerCase().replace(/\s+/g,"").replace(/[。.%％]/g,"")}
function checkLesson(){ $$("#lessonBody [data-answer]").forEach(input=>{const ok=normAnswer(input.value)===normAnswer(input.dataset.answer)||normAnswer(input.value).includes(normAnswer(input.dataset.answer));const tip=input.nextElementSibling;tip.textContent=ok?"✅ 答对啦":"参考答案："+input.dataset.answer;tip.className=ok?"ok":"no"})}
$("#finishLesson").onclick=e=>{e.preventDefault();$("#lessonDialog").close();openScore(currentSubject)}
function renderPlan(){const now=position().week;$("#planList").innerHTML=PLAN_TOPICS.map((w,i)=>`<details class="week-card" ${i===now?"open":""}><summary><span>第${i+1}周 · ${w[0]}</span><b>${i<now?"✓":i===now?"进行中":""}</b></summary><div class="week-days">${DAY_ACTIONS[0].map((_,d)=>`<div><strong>第${d+1}天${d===6?" · 复盘":""}</strong>${[0,1,2].map(si=>`<p>${Object.values(SUBJECTS)[si].icon} ${planTask(i,d,si)}</p>`).join("")}</div>`).join("")}</div></details>`).join("")}
function renderAll(){const r=todayRecords(),ss=Object.values(r).map(x=>x.score),total=ss.length?Math.round(ss.reduce((a,b)=>a+b,0)/ss.length):0;$("#totalScore").textContent=total;$("#scoreRing").style.background=`conic-gradient(var(--purple) ${total*3.6}deg,#ece9f7 0)`;$("#doneCount").textContent=`${ss.length}/3 已完成`;const all=Object.values(data.records).flatMap(x=>Object.values(x)),stars=all.reduce((n,x)=>n+Math.round(x.score/10),0);$("#stars").textContent=stars;$("#encouragement").textContent=total>=90?"太棒了！认真和坚持都在发光。":total>=75?"稳稳进步中，订正会让知识更牢。":ss.length?"今天已经迈出很棒的一步！":"完成一项任务，点亮今天吧！";let streak=0,d=new Date();while(data.records[dateKey(d)]&&Object.keys(data.records[dateKey(d)]).length){streak++;d.setDate(d.getDate()-1)}$("#streak").textContent=streak;renderGrowth(stars,streak);renderReport()}
function openScore(id){currentSubject=id;const s=SUBJECTS[id],old=todayRecords()[id];$("#modalIcon").textContent=s.icon;$("#modalTitle").textContent=s.name;$("#scoreFields").innerHTML=RUBRIC.map(([n,max],i)=>`<div class="score-row"><label><span>${n}</span><b id="v${i}">${old?.parts?.[i]??max}</b> / ${max}</label><input type="range" min="0" max="${max}" value="${old?.parts?.[i]??max}" data-range="${i}"></div>`).join("");$$("[data-range]").forEach(r=>r.oninput=updatePreview);updatePreview();$("#scoreDialog").showModal()}
function updatePreview(){let t=0;$$("[data-range]").forEach((r,i)=>{$(`#v${i}`).textContent=r.value;t+=+r.value});$("#previewScore").textContent=t}
$("#saveScore").onclick=e=>{e.preventDefault();data.records[today()]||={};const parts=$$("[data-range]").map(r=>+r.value);data.records[today()][currentSubject]={score:parts.reduce((a,b)=>a+b,0),parts,task:assigned(currentSubject)};save();$("#scoreDialog").close();renderTasks();renderAll()};
$$(".tabs button").forEach(b=>b.onclick=()=>{$$(".tabs button,.page").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(`#${b.dataset.page}`).classList.add("active")});
function count(id){return Object.values(data.records).filter(r=>r[id]).length}
function renderGrowth(stars,streak){const levels=["初醒嫩芽","好奇幼苗","勤学花苞","知识繁花","探索之星"],idx=Math.min(4,Math.floor(stars/100));$("#levelName").textContent=levels[idx];$("#levelProgress").style.width=`${idx===4?100:stars%100}%`;$("#levelHint").textContent=idx===4?"已经到达最高等级！":`再获得 ${100-stars%100} 颗星升级`;const defs=[["🌱","第一次打卡",stars>0],["🔥","连续3天",streak>=3],["🏆","三科全优",Object.values(todayRecords()).filter(x=>x.score>=90).length===3],["📚","语文达人",count("chinese")>=5],["🧠","数学达人",count("math")>=5],["🎤","英语达人",count("english")>=5]];$("#badges").innerHTML=defs.map(x=>`<div class="badge ${x[2]?"earned":""}"><span>${x[0]}</span><small>${x[1]}</small></div>`).join("");let bars=[];for(let i=6;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);let v=Object.values(data.records[dateKey(d)]||{}),avg=v.length?Math.round(v.reduce((a,b)=>a+b.score,0)/v.length):0;bars.push(`<div class="bar"><i style="height:${Math.max(3,avg)}px"></i>${["日","一","二","三","四","五","六"][d.getDay()]}</div>`)}$("#weekChart").innerHTML=bars.join("")}
function renderReport(){let dates=[];for(let i=6;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);dates.push(dateKey(d))}const stats={};Object.keys(SUBJECTS).forEach(id=>{const v=dates.map(d=>data.records[d]?.[id]?.score).filter(Number.isFinite);stats[id]=v.length?Math.round(v.reduce((a,b)=>a+b,0)/v.length):0});const active=Object.values(stats).filter(Boolean),avg=active.length?Math.round(active.reduce((a,b)=>a+b,0)/active.length):0,best=Object.keys(stats).sort((a,b)=>stats[b]-stats[a])[0],weak=Object.keys(stats).filter(x=>stats[x]).sort((a,b)=>stats[a]-stats[b])[0];$("#weekScore").textContent=avg;$("#summaryText").textContent=!active.length?"完成学习后，这里会生成专属总结。":`本周整体表现${avg>=90?"非常出色":avg>=75?"稳步向上":"正在积累"}，${SUBJECTS[best].name}表现最亮眼。`;$("#subjectStats").innerHTML=Object.entries(SUBJECTS).map(([id,s])=>`<div class="stat"><span>${s.icon} ${s.name}</span><b>${stats[id]||"--"}${stats[id]?" 分":""}</b></div>`).join("");$("#nextGoal").textContent=weak?`重点照顾${SUBJECTS[weak].name}：完成基础任务后，再用10分钟复习错题。`:"先完成今天的三科学习任务。"}
$("#parentBtn").onclick=()=>{$("#pinInput").value="";$("#pinError").textContent="";$("#pinDialog").showModal()};$("#unlockParent").onclick=e=>{e.preventDefault();if($("#pinInput").value!==data.pin){$("#pinError").textContent="密码不正确，请再试一次。";return}$("#pinDialog").close();openParent()};
function openParent(){$("#childName").value=data.name;$("#startDate").value=data.start;$("#newPin").value="";$("#taskEditors").innerHTML=Object.entries(SUBJECTS).map(([id,s])=>`<label class="editor">${s.icon} 今日${s.name}任务<input type="text" data-edit="${id}" value="${assigned(id)}"></label>`).join("");$("#parentDialog").showModal()}
$("#saveSettings").onclick=e=>{e.preventDefault();const pin=$("#newPin").value;if(pin&&!/^\d{4}$/.test(pin)){alert("新密码必须是4位数字。");return}data.name=$("#childName").value.trim()||"小小探索家";data.start=$("#startDate").value||today();if(pin)data.pin=pin;data.tasks[today()]={};$$("[data-edit]").forEach(x=>data.tasks[today()][x.dataset.edit]=x.value.trim());save();$("#parentDialog").close();init()};
function download(name,text,type){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
$("#exportJson").onclick=()=>download(`星芽学习记录-${today()}.json`,JSON.stringify(data,null,2),"application/json");$("#exportCsv").onclick=()=>{const rows=[["日期","科目","任务","得分",...RUBRIC.map(x=>x[0])]];Object.entries(data.records).sort().forEach(([date,r])=>Object.entries(r).forEach(([id,x])=>rows.push([date,SUBJECTS[id].name,x.task||"",x.score,...(x.parts||[])])));download(`星芽学习评分-${today()}.csv`,rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n"),"text/csv")};
$("#clearData").onclick=()=>{if(confirm("确定清空全部学习记录吗？此操作无法恢复。")){localStorage.removeItem(KEY);location.reload()}};$("#resetToday").onclick=()=>{if(confirm("要重新填写今天的评分吗？")){delete data.records[today()];save();renderTasks();renderAll()}};init();
